project:
  type: website
  output-dir: _render
  render:
    - "*.qmd"
    - "!handouts/exercises_Day3_answer.qmd"
website:
  cookie-consent:
    type: express
    style: simple
    palette: dark
  google-analytics:
    tracking-id: "G-3EXJ6W4CBC"
    anonymize-ip: true
  title: "OUCRU introduction to Medical Statistics"
  favicon: "site_imgs/OUCRU.jpg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/IntroductionRDay1.qmd
        text: Intro to R (day 1)
      - href: slides/IntroductionRDay2.qmd
        text: Intro to R (day 2)
      - href: slides/viz.qmd
        text: Principles of data visualisation
      - href: slides/advance_r.qmd
        text: Advance R topics
      - href: slides/qt-repro-res.qmd
        text: Using Quarto for reproducible research

toc: true
number-sections: true

execute: 
  echo: true

format:
  html:
    theme: cosmo
  revealjs:
    css: ../styles.css