project:
  type: website
  output-dir: _render
  
website:
  title: "OUCRU R training 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/IntroductionRDay1.qmd
        text: Intro to R (day 1)
      - href: slides/IntroductionRDay2.qmd
        text: Intro to R (day 2)
      - href: slides/viz.qmd
        text: Principles of data visualisation
      - href: slides/advance_r.qmd
        text: Advance R topics
      - href: slides/quarto.qmd
        text: Using Quarto for reproducible research

toc: true
number-sections: true

execute: 
  echo: true

format:
  html:
    theme: cosmo
  revealjs:
    css: ../styles.css