project:
  type: website
  output-dir: _render
  render:
    - "*.qmd"
    - "others/*.qmd"
    - "!handouts/day_2/Exercise4_RStudio.qmd"
  resources:
    - "handouts/"
    - "slides/"
    - "site_imgs/"
keywords: ["Medical Statistics", "OUCRU", "Biostatistics", "R Programming", "Clinical Research"]

website:
  title: "Medical Statistics"
  description: "Introduction to Medical Statistics course by OUCRU. Learn biostatistics, R programming, and data analysis for clinical research."
  site-url: "https://tranhung93.github.io/Introduction-to-Medical-Statistics/"
  
  cookie-consent:
    type: express
    style: simple
    palette: dark
  google-analytics:
    tracking-id: "G-3EXJ6W4CBC"
    anonymize-ip: true
  favicon: "site_imgs/OUCRU.jpg"
  navbar:
    pinned: true
    logo: "site_imgs/OUCRU.jpg"    
    left:
      - href: index.qmd
        text: Home
      - href: others/medical_statistics_2024.qmd 
        text: Course Videos
      - href: others/other_resources.qmd
        text: Additional R Resources
        

  comments:
    giscus:
      repo: "TranHung93/Introduction-to-Medical-Statistics"
      repo-id: "R_kgDORlzZ2Q"
      category: General
      category-id: "DIC_kwDORlzZ2c4C4qDV"
      mapping: pathname
      reactions-enabled: true
      loading: lazy
      input-position: top
      theme: light # You can also use 'dark' or 'auto'
      

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2026 Tran Thai Hung and the Biostatistics group <br></span>
      <span class="faux-block">Contact: [hungtt@oucru.org](mailto:hungtt@oucru.org) <br></span>      
      <span class="faux-block">All content licensed under [Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    center: |
     
    right: |
      <span class="faux-block"><a href="https://github.com/TranHung93/Introduction-to-Medical-Statistics">View source on GitHub</a></span>

toc: true
number-sections: true

execute: 
  echo: true

format:
  html:
    theme: cosmo
    include-after-body: comment-header.html
  revealjs:
    css: styles.css