---
format: 
  html:
    link-external-icon: true
    link-external-newwindow: true
from: markdown+autolink_bare_uris
number-depth: 1
toc-depth: 2
date: last-modified
date-format: "MMMM D, YYYY"
---

# Welcome! {.unnumbered}

::: {.column-margin}
### Course Objectives
* **Concepts:** Hypothesis tests, p-values, & confidence intervals.
* **Methods:** t-tests, chi-square, linear & logistic regression.
* **Skills:** Perform and interpret basic statistical analyses.
:::

Welcome to the **OUCRU Introduction to Medical Statistics 2026**. This course is designed to provide clinicians and researchers with the fundamental statistical tools required for medical research.

[Welcome note](handouts/0_welcome.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}

::: {.callout-note appearance="simple"}
## 📅 Logistics & Schedule
-   **Time:** 09:15 – 16:45 (UTC +7) daily
-   **Lunch Break:** 12:30 – 13:30 (UTC +7)
-   **Full Schedule:** [Timetable](handouts/Agenda_StatCourse_23-27March2026.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}
-   *Note: Lunch is provided for in-person attendees.*
:::

## Contributors {.unnumbered}

::: {layout-ncol="2"}
-   **Prof. Ronald Geskus**
-   **Dr. Duc Du Hong**
-   **Dr. Hoang Van Thuan**
-   **Dr. Nguyen Lam Vuong**
-   **Dr. Tran Thai Hung**
:::

------------------------------------------------------------------------

# Pre-course Setup

::: callout-tip
## 🛠️ Choose Your Environment

You have two ways to follow the course exercises:

1.  **Zero Setup:** Use the **Web-R** versions directly in your browser.
2.  **Local Setup:** If you prefer using **RStudio**, please complete the [Pre-course Setup Handout](others/precourse_setup.qmd){.btn .btn-outline-primary .btn-sm target="_blank"} before joining.
:::

# Course Topics

**Course handout:** [Course handout](handouts/CourseHandouts.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}; [Dictionary](handouts/Dictionary_for_statistical_terms_in_Vietnamese.xlsx){.btn .btn-outline-primary .btn-sm target="_blank"}

## Day 1: Descriptive and Exploratory Data Analysis

<details>
<summary>[Click to view the materials]{style="color:blue"}</summary>

::: {.panel-tabset}

### ☀️ Morning: Descriptive Analysis

::: {layout-ncol="2"}
#### Contents

1.  Data characteristics & Variable types
2.  Numerical & Graphical summaries
3.  Intro to R and RStudio
<div id="QR1">
  <button class="btn btn-primary" onclick="unlockSession('306', 'QR1', 
    '<a href=\'./handouts/QR_code/01.png\' class=\'btn btn-success btn-sm\' target=\'_blank\'>QR code</a>')">
    Click to unlock QR code
  </button>
</div>

#### Materials 

-   **Lecture:** [Slides](slides/day_1/1.SlidesDescriptives.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Exercises:**
    -   [Web-R version](handouts/day_1/ExerciseWebr-1.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_1/ExerciseRStudio-1.html){.btn .btn-outline-primary .btn-sm target="_blank"} [Script](handouts/day_1/ExerciseCode-1.R){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Answers:** 
<!-- <div id="day1-morning"> -->
<!--   <button class="btn btn-primary" onclick="unlockSession('TooEasy?', 'day1-morning',  -->
<!--     '<a href=\'./handouts/day_1/ExerciseWebrAnswers-1.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>Web-R Answers</a> ' + -->
<!--     '<a href=\'./handouts/day_1/ExerciseRStudioAnswers-1.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>RStudio Answers</a>')"> -->
<!--     Click to unlock answer -->
<!--   </button> -->
<!-- </div> -->
    -   [Web-R version](handouts/day_1/ExerciseWebrAnswers-1.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_1/ExerciseRStudioAnswers-1.html){.btn .btn-outline-primary .btn-sm target="_blank"}

:::


### 🌤️ Afternoon: Exploratory Analysis

::: {layout-ncol="2"}
#### Contents

1.  Baseline tables
2.  Graphs for categorical variables
3.  Numeric variables by group
4.  2-variable numeric plots
<div id="QR2">
  <button class="btn btn-primary" onclick="unlockSession('306', 'QR2', 
    '<a href=\'./handouts/QR_code/02.png\' class=\'btn btn-success btn-sm\' target=\'_blank\'>QR code</a>')">
    Click to unlock QR code
  </button>
</div>

#### Materials

-   **Lecture:** [Slides](slides/day_1/2.SlidesEDA.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Exercises:**
    -   [Web-R version](handouts/day_1/ExerciseWebr-2.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_1/ExerciseRStudio-2.html){.btn .btn-outline-primary .btn-sm target="_blank"} [Script](handouts/day_1/ExerciseCode-2.R){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Answers:** 
<!-- <div id="day1-afternoon"> -->
<!--   <button class="btn btn-primary" onclick="unlockSession('RealFun!', 'day1-afternoon',  -->
<!--     '<a href=\'./handouts/day_1/ExerciseWebrAnswers-2.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>Web-R Answers</a> ' + -->
<!--     '<a href=\'./handouts/day_1/ExerciseRStudioAnswers-2.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>RStudio Answers</a>')"> -->
<!--     Click to unlock answer -->
<!--   </button> -->
<!-- </div> -->
    -   [Web-R version](handouts/day_1/ExerciseWebrAnswers-2.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_1/ExerciseRStudioAnswers-2.html){.btn .btn-outline-primary .btn-sm target="_blank"}

:::

:::

</details>



## Day 2: Statistical analysis principles, Distributions, Confidence Intervals

<details>
<summary>[Click to view the materials]{style="color:blue"}</summary>

::: {.panel-tabset}

### ☀️ Morning: Main principles & Binomial

::: {layout-ncol="2"}
#### Contents

1. Types of study questions
2. Sampling variation
3. Binomial distribution
4. Testing hypotheses
<div id="QR3">
  <button class="btn btn-primary" onclick="unlockSession('306', 'QR3', 
    '<a href=\'./handouts/QR_code/03.png\' class=\'btn btn-success btn-sm\' target=\'_blank\'>QR code</a>')">
    Click to unlock QR code
  </button>
</div>

#### Materials
-   **Lecture:** [Slides](slides/day_2/3.SlidesStatisticsPrinciples.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Exercises:**
    -   [Web-R version](handouts/day_2/ExerciseWebr-3.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_2/ExerciseRStudio-3.html){.btn .btn-outline-primary .btn-sm target="_blank"} [Script](handouts/day_2/ExerciseCode-3.R){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Answers:** 
<!-- <div id="day2-morning"> -->
<!--   <button class="btn btn-primary" onclick="unlockSession('TheBasic', 'day2-morning',  -->
<!--     '<a href=\'./handouts/day_2/ExerciseWebrAnswers-3.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>Web-R Answers</a> ' + -->
<!--     '<a href=\'./handouts/day_2/ExerciseRStudioAnswers-3.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>RStudio Answers</a>')"> -->
<!--     Click to unlock answer -->
<!--   </button> -->
<!-- </div> -->
    -   [Web-R version](handouts/day_2/ExerciseWebrAnswers-3.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_2/ExerciseRStudioAnswers-3.html){.btn .btn-outline-primary .btn-sm target="_blank"}


:::

### 🌤️ Afternoon: Normal & Confidence Intervals

::: {layout-ncol="2"}
#### Contents

1.  The normal distribution
2.  Confidence intervals
3.  Hypothesis tests and p-values
<div id="QR4">
  <button class="btn btn-primary" onclick="unlockSession('306', 'QR4', 
    '<a href=\'./handouts/QR_code/04.png\' class=\'btn btn-success btn-sm\' target=\'_blank\'>QR code</a>')">
    Click to unlock QR code
  </button>
</div>

#### Materials

-   **Lecture:** [Slides](slides/day_2/4_MainConceptsPrinciples.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Exercises:**
    -   [Web-R version](handouts/day_2/Exercise4Webr.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_2/Exercise4_RStudio.qmd){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Answers:**
<!-- <div id="day2-afternoon"> -->
<!--   <button class="btn btn-primary" onclick="unlockSession('Useless?', 'day2-afternoon',  -->
<!--     '<a href=\'./handouts/day_2/Exercise4Answer_Webr.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>Web-R Answers</a> ' + -->
<!--     '<a href=\'./handouts/day_2/Exercise4Answer_RStudio.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>RStudio Answers</a>')"> -->
<!--     Click to unlock answer -->
<!--   </button> -->
<!-- </div> -->
    -   [Web-R version](handouts/day_2/Exercise4Answer_Webr.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_2/Exercise4Answer_RStudio.html){.btn .btn-outline-primary .btn-sm target="_blank"}

:::

:::

</details>

## Day 3: Comparing continuous variables and Simple linear regression

<details>
<summary>[Click to view the materials]{style="color:blue"}</summary>

::: {.panel-tabset}

### ☀️ Morning: Comparing continuous variables

::: {layout-ncol="2"}
#### Contents

1.  Student’s t-test vs. Wilcoxon rank-sum test
2.  Paired t-test vs. Wilcoxon signed-rank test
<div id="QR5">
  <button class="btn btn-primary" onclick="unlockSession('306', 'QR5', 
    '<a href=\'./handouts/QR_code/05.png\' class=\'btn btn-success btn-sm\' target=\'_blank\'>QR code</a>')">
    Click to unlock QR code
  </button>
</div>

#### Materials

-   **Lecture:** [Slides](slides/day_3/5_Group comparison_Slides.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Exercises:**
    -   [Web-R version](handouts/day_3/Exercise5_Webr.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_3/Exercise5_RStudio.html){.btn .btn-outline-primary .btn-sm target="_blank"} [Script](handouts/day_1/ExerciseCode.R){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Answers:**
<!-- <div id="day3-morning"> -->
<!--   <button class="btn btn-primary" onclick="unlockSession('Testing', 'day3-morning',  -->
<!--     '<a href=\'./handouts/day_3/Exercise5_Answers.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>Web-R Answers</a> ' + -->
<!--     '<a href=\'./handouts/day_3/Exercise5_Answers.pdf\' class=\'btn btn-success btn-sm\' target=\'_blank\'>RStudio Answers</a>')"> -->
<!--     Click to unlock answer -->
<!--   </button> -->
<!-- </div> -->
    -   [Web-R version](handouts/day_3/Exercise5_Answers.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_3/Exercise5_Answers.pdf){.btn .btn-outline-primary .btn-sm target="_blank"} 

:::


### 🌤️ Afternoon: Simple linear regression

::: {layout-ncol="2"}
#### Contents

1.  Visualizing Relationships
2.  The Linear Regression Model
3.  Interpreting Results
4.  Regression Diagnostics
<div id="QR6">
  <button class="btn btn-primary" onclick="unlockSession('306', 'QR6', 
    '<a href=\'./handouts/QR_code/06.png\' class=\'btn btn-success btn-sm\' target=\'_blank\'>QR code</a>')">
    Click to unlock QR code
  </button>
</div>

#### Materials

-   **Lecture:** [Slides](slides/day_3/6.simpleLinearRegression_Slides.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Exercises:**
    -   [Web-R version](handouts/day_3/Exercise6_Webr.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_3/Exercise6_RStudio.html){.btn .btn-outline-primary .btn-sm target="_blank"} [Script](handouts/day_1/Exercise6Code.R){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Answers:**
<!-- <div id="day3-afternoon"> -->
<!--   <button class="btn btn-primary" onclick="unlockSession('LinearTrend', 'day3-afternoon',  -->
<!--     '<a href=\'./handouts/day_3/Exercise6_Answers.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>Web-R Answers</a> ' + -->
<!--     '<a href=\'./handouts/day_3/Exercise6_Answers.pdf\' class=\'btn btn-success btn-sm\' target=\'_blank\'>RStudio Answers</a>')"> -->
<!--     Click to unlock answer -->
<!--   </button> -->
<!-- </div> -->
    -   [Web-R version](handouts/day_3/Exercise6_Answers.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_3/Exercise6_Answers.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}

:::

:::

</details>


## Day 4: Multivariable linear and logistic regression

<details>
<summary>[Click to view the materials]{style="color:blue"}</summary>

::: {.panel-tabset}

### ☀️ Morning: Multivariable linear regression

::: {layout-ncol="2"}
#### Contents

1. Model formulation
2. Estimation
3. Testing
<div id="QR7">
  <button class="btn btn-primary" onclick="unlockSession('306', 'QR7', 
    '<a href=\'./handouts/QR_code/07.png\' class=\'btn btn-success btn-sm\' target=\'_blank\'>QR code</a>')">
    Click to unlock QR code
  </button>
</div>

#### Materials

-   **Lecture:** [Slides](slides/day_4/7.multipleRegression.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Exercises:**
    -   [Web-R version](handouts/day_4/Exercise7_Webr.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_4/Exercise7_RStudio.html){.btn .btn-outline-primary .btn-sm target="_blank"} [Script](handouts/day_4/Exercise7Code.R){.btn .btn-outline-primary .btn-sm target="_blank"}    
-   **Answers:**
<div id="day4-morning">
  <button class="btn btn-primary" onclick="unlockSession('MoreLinear', 'day4-morning', 
    '<a href=\'./handouts/day_4/Exercise7-Answer-Webr.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>Web-R Answers</a>')">
    Click to unlock answer
  </button>
</div>


:::


### 🌤️ Afternoon: Logistic regression

::: {layout-ncol="2"}
#### Contents

1.  Risk/odds, risk ratio (RR)/odds ratio (OR)
2.  Logistic regression model
3.  Interpreting Univariable Logistic Regression
4.  Interpreting Multivariable Logistic Regression
<div id="QR8">
  <button class="btn btn-primary" onclick="unlockSession('306', 'QR8', 
    '<a href=\'./handouts/QR_code/08.png\' class=\'btn btn-success btn-sm\' target=\'_blank\'>QR code</a>')">
    Click to unlock QR code
  </button>
</div>

#### Materials

-   **Lecture:** [Slides](slides/day_4/8.Logistic Regression_Slides.pdf){.btn .btn-outline-primary .btn-sm target="_blank"}
-   **Exercises:**
    -   [Web-R version](handouts/day_4/Exercise8_Webr.html){.btn .btn-outline-primary .btn-sm target="_blank"}
    -   [RStudio version](handouts/day_4/Exercise8_RStudio.html){.btn .btn-outline-primary .btn-sm target="_blank"} [Script](handouts/day_4/Exercise8Code.R){.btn .btn-outline-primary .btn-sm target="_blank"} 
-   **Answers:**
<div id="day4-afternoon">
  <button class="btn btn-primary" onclick="unlockSession('LogOdds', 'day4-afternoon', 
    '<a href=\'./handouts/day_4/Exercise8_Answers.html\' class=\'btn btn-success btn-sm\' target=\'_blank\'>Web-R Answers</a> ' +
    '<a href=\'./handouts/day_4/Exercise8_Answers.pdf\' class=\'btn btn-success btn-sm\' target=\'_blank\'>RStudio Answers</a>')">
    Click to unlock answer
  </button>
</div>


:::

:::

</details>




<!-- <script> -->

<!-- function unlockSession(correctPassword, elementId, linksHtml) { -->
<!--   var password = prompt("Please enter the session code provided in class:"); -->

<!--   if (password === correctPassword) { -->
<!--     document.getElementById(elementId).innerHTML = linksHtml; -->
<!--   } else if (password !== null && password !== "") { -->
<!--     alert("Incorrect code."); -->
<!--   } -->
<!-- } -->

<!-- </script> -->


