---
title: Introduction to R 2025, Day 2
author: "Ronald Geskus and Thinh Ong Phuc"
engine: knitr
format-links: 
  - html
toc: false
number-sections: false
webr:
  channel-type: "shared-array-buffer"
  cell-options:
    autorun: false
    message: true
    warning: true
    eval: true
    echo: false
format:
  revealjs:
    slide-number: true
    logo: "figures/OUCRU.jpg"
    preview-links: true
    theme: solarized
    transition: fade
    show-slide-number: print
    embed-resources: true
    include-in-header: 
      - text: |
          <script src='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/js/all.js'></script>
filters: 
  - webr
  - assign
profile: 
  default: assign
---

## Learning goals {.smaller} 

- Day 1
  - Basic structure of the R program and language
  - Use the RStudio working environment	
  - Import, inspect and manage a data set
    - Select variables (columns) and rows (observations)
	- Missing data, factors, dates

::: {.fragment .highlight-red}
- Day 2
  - Functions
  - Visualisations using graphics in base R
  - Object specific functions
  - Finding further information
::: 


# Functions

## Basic format {.smaller .scrollable}

- All actions are performed via functions: 
  `sqrt`, `mean`, `help`, `library`, `t.test`, `plot`

- Input: *required* and *optional* arguments; within parentheses, separated by comma
  - required: need to be supplied
  - optional: have default values

    Beware of sequence of arguments; required ones come first

	```{webr-r}
	log(1000)           # natural log, does not give 3
    help(log)
    log(1000, 10) 
    log(10, 1000)       # gives 1000-log of 10
    log(base=10, x=1000) # x required, base optional
    log(b=10,x=1000)     # Argument names can be abbreviated if no risk of ambiguity
	```
- Special "argument": `...`
  
  anything that makes sense, e.g. `...` in `c` and `paste` function

- Output: result of calculations (typically assigned to R object), graphics, help
   window, etc.

- You can use functions within other functions, e.g. `mean(c(3,6,8))`

## Functions: the inside {.smaller}

- Function code can be seen by leaving out the parentheses \texttt{( )}
```{webr-r}
IQR
```
- General structure: 

```{.r}
FunctionName(args) {
    lines of R code (collection of functions)
}
```

The last value is returned as output
- You can write your own functions:

```{webr-r}
good.morning <- function(work){
    if(work==TRUE) cat("wake up") else 
      cat("you can stay in bed")
}
good.morning()
```

# Basic data visualisations

## R graphics systems:

- Base graphics (package *graphics*)
  - Simple to use
  - Always loaded when R is started
  - See Ch.\ 12 of manual [An Introduction to R](https://cran.r-project.org/doc/manuals/R-intro.pdf)
	
::: {.fragment}
- lattice package. Less popular nowadays. Not covered here. 
- ggplot2 package: Wednesday morning
- Note: these systems cannot be mixed
- Each of these systems has many packages with extensions
:::

## Basic plot in base graphics {.smaller}


1. Plot fare paid as function of age
```{.r}
plot(titanic$age, titanic$fare)
```
What would you like to change to make it good enough for publication? 

::: {.fragment}
labels, rotate numbers along y-axis, scale
::: 

::: {.fragment}
- Formula based specification
    - general form: `dependent ~ independent`
    - independent: variable names separated by operator (mostly `+` and `*`)
    - functions with formula (as first argument) have `data` and `subset` argument
    - basis for specification of regression models
-  [Good summary on base graphics (page 5)](http://cran.r-project.org/doc/contrib/Baggott-refcard-v2.pdf){target="_blank"}
:::


## Some important functions for plotting ##

- High level plot functions
  - `plot`
  - `hist`
  - `boxplot`
  
- Low level plot functions (add to existing plot)
  - `points`
  - `lines`, `abline`
  - `text`, `legend`, `title`, `arrows`

## Other plots

1. Plot fare paid as function of age
```{.r}
plot(titanic$age, titanic$fare)
```

2. Make a histogram of age

::: {fragment}
3. Make a boxplot of fare by passenger class. 
  
   There are high values for fare that disturb the plot. Therefore, only show the
fare up to 300 British Pounds.
:::


## Arguments and parameters that can be changed ##

- Within function only
  - `xlab`, `ylab`, `main`
  - `type`
  - `xlim`, `ylim`, `log`
  
- Also via `par` function
  - `cex.axis`, `cex.lab`, `las`
  - `cex`, `pch`
  - `col`, `lty`, `lwd`, `cex`

- Only via `par`
  - `mar`, `mfcol`, `mfrow`


## Export: two types of formats {.smaller}

- Vector format (pdf, eps, wmf, emf)
  - digital image consisting of independent geometric objects
        (segments, polygons, curves, etc.)
  - can be enlarged without losing resolution
- Raster (png, jpeg, tiff).
  - rectangular grid of pixels, possibly with color
  - resolution impaired if image is enlarged
- Graphics can be saved via the menu in the graphics/plots window, or
    a specific graphics file type can be created directly (via
    `pdf("foo.pdf",...)`, or `win.metafile("foo.wmf",...)` or
    `png("foo.png",...)` and ending with `dev.off()`)
	
## Structure of R {.smaller}

- **Objects**: data, functions, results analysis

- **Environment**: a collection of objects that is accessible in R session.
  1. Our "Workspace": objects we create/import RStudio: **Global Environment** in
        **Environment** pane
  2. Packages with existing functions and data sets: **base**,
        **stats**, **graphics**
  3. When a package is loaded, a new environment is created

     Listing of environments shown in RStudio via drop-down list under **Global
    Environment** in **Environment** pane
- Hierarchical structure of environments; needed for dealing with duplicate names
	
## R resembles operating system

| R                               |  operating system           |
|---------------------------------|-----------------------------|
| objects                         | files                       |
| Workspace                       | current folder              |
| environments                    | folders in "path" variable  |
| **Environment** pane in RStudio | Explorer window             |


## Classes and Methods 

- R is object-oriented: Many objects have a class
- *Constructor*: function that creates object of given class, e.g. `data.frame`,
    `factor`, `as.Date`, most statistical modelling functions, e.g. `t.test`, `lm`
- *Generic functions* have methods for specific classes. Example:
  -   `summary`: `summary.data.frame, summary.Date` default: `summary.default`
  -   `plot`: `plot(y ~ x, data=..., ...)`
        Plot depends on class of `x`: scatterplot is default, but
        boxplot if `x` is of class factor

## Finding Information {.smaller}

-   Function `help`. R is object oriented!

-   Function `help.search`. Only search in installed packages

-   Search on Google (using `language r:`)

-   [R documentation](https://www.rdocumentation.org), [Rseek](http://rseek.org)

-   [R-universe](https://r-universe.dev/search)

-   chatGPT or  [askgpt](https://www.johannesbgruber.eu/post/2023-04-02-introducing-askgpt-a-chat-interface-that-helps-you-to-learn-r/)
    and

-   CRAN (Task Views, Vignettes, list with packages)
    [CRANsearcher](https://github.com/RhoInc/CRANsearcher) in RStudio

-   Search in R mailing lists on [Markmail](http://r-help.markmail.org)

-   [Stack Overflow](http://stackoverflow.com/questions/tagged/r)

-   Have a look at the links provided at the end of the handout

-   [Some further suggestions](https://blog.rsquaredacademy.com/getting-help-in-r-updated/)
	
	
## Lists {.smaller}

- Modes cannot be mixed in vectors
```{webr-r}
teacher <- c("Ronald","Thinh","Tuyen")
room <- c(306,305,305)
c(teacher, room)
```
- Modes can be mixed in a list:

```{webr-r}
list(teacher, room)
list(teacher = teacher, room = room)
```
Two *components*, with names `teacher` and `room` 

- Data are of mode list, but with a special class `data.frame`
```{webr-r}
mode(titanic)
class(titanic)
```

## The apply  functions

- `apply`

- `lapply`: apply a function over a list or vector

- `sapply`: similar to `lapply` but more user-friendly if output can
    be coerced into a vector

- `tapply`: can be used to split a vector in subgroups and apply a
    function to each of the subgroups

- `mapply`: apply a function to multiple list or vector arguments
