---
title: "Course Video Archive"
subtitle: "Recordings from the 2024 Iteration"
toc: false
number-sections: false
format: 
  html:
    link-external-newwindow: true
    link-external-icon: true
    page-layout: full
date: last-modified
date-format: "MMMM D, YYYY"
---

::: {.callout-important appearance="simple"}
These recordings are from the **previous iterations** of the course. Links for the **future iteration** will be uploaded here shortly after the course concludes.
:::

## 📺 2026 Medical Statistics Lecture Recordings

### Full series:
[**Watch Session**](https://www.youtube.com/playlist?list=PLrVt1KgflEGuOPPSk0MCrHFS-6qiHqABq){.btn .btn-outline-primary .btn-sm}

## 📺 2025 R training Lecture Recordings

### Full series:
[**Watch Session**](https://www.youtube.com/playlist?list=PLrVt1KgflEGvCbAlMwftGe3g_WoqaR13C){.btn .btn-outline-primary .btn-sm}


## 📺 2024 Medical Statistics Lecture Recordings

::: {layout-ncol=2}

### Day 1: Descriptives & EDA
[**Watch Session**](https://youtu.be/f4bBIMs5w08){.btn .btn-outline-primary .btn-sm}

### Day 2: Statistical Principles & Distributions
[**Watch Session**](https://youtu.be/DXEC9z0FQpM){.btn .btn-outline-primary .btn-sm}

### Day 3: Group Comparisons & Simple Modeling
[**Part 1**](https://youtu.be/ThvKyzUIeZY){.btn .btn-outline-primary .btn-sm} [**Part 2**](https://youtu.be/cWA-BrcN0kM){.btn .btn-outline-primary .btn-sm}

### Day 4: Multivariable & Logistic Regression
[**Part 1**](https://youtu.be/8zJkYpFUqRI){.btn .btn-outline-primary .btn-sm} [**Part 2**](https://youtu.be/O8rZbQaIBi8){.btn .btn-outline-primary .btn-sm}

### Day 5: Study Design & Research Methodology
[**Watch Session**](https://youtu.be/5ajIkOWAI9Q){.btn .btn-outline-primary .btn-sm}

:::

---

